import { Program } from './types';

export const PROGRAMS: Omit<Program, 'id'>[] = [
  {
    name: 'PPL — Push Pull Legs (6-Day)',
    description: 'The most popular hypertrophy program. Train 6 days/week with push, pull, and legs twice per week.',
    days_per_week: 6,
    difficulty: 'intermediate',
    program_days_json: [
      {
        day_number: 1,
        label: 'Push A',
        muscle_groups: ['Chest', 'Shoulders', 'Triceps'],
        exercises: [
          { exercise_name: 'Barbell Bench Press', sets: 4, reps: '6-8', rest_seconds: 180 },
          { exercise_name: 'Incline Dumbbell Press', sets: 3, reps: '8-12', rest_seconds: 120 },
          { exercise_name: 'Cable Flyes', sets: 3, reps: '12-15', rest_seconds: 90 },
          { exercise_name: 'Overhead Press (OHP)', sets: 3, reps: '8-10', rest_seconds: 150 },
          { exercise_name: 'Lateral Raise', sets: 4, reps: '15-20', rest_seconds: 60 },
          { exercise_name: 'Tricep Pushdown', sets: 3, reps: '12-15', rest_seconds: 60 },
          { exercise_name: 'Skull Crusher', sets: 3, reps: '10-12', rest_seconds: 90 },
        ],
      },
      {
        day_number: 2,
        label: 'Pull A',
        muscle_groups: ['Back', 'Biceps', 'Rear Delts'],
        exercises: [
          { exercise_name: 'Deadlift', sets: 4, reps: '4-6', rest_seconds: 240 },
          { exercise_name: 'Barbell Row', sets: 4, reps: '6-8', rest_seconds: 180 },
          { exercise_name: 'Pull-Up', sets: 3, reps: '6-10', rest_seconds: 150 },
          { exercise_name: 'Seated Cable Row', sets: 3, reps: '10-12', rest_seconds: 90 },
          { exercise_name: 'Face Pull', sets: 3, reps: '15-20', rest_seconds: 60 },
          { exercise_name: 'Barbell Curl', sets: 3, reps: '8-10', rest_seconds: 90 },
          { exercise_name: 'Hammer Curl', sets: 3, reps: '12-15', rest_seconds: 60 },
        ],
      },
      {
        day_number: 3,
        label: 'Legs A',
        muscle_groups: ['Quads', 'Hamstrings', 'Calves', 'Glutes'],
        exercises: [
          { exercise_name: 'Barbell Back Squat', sets: 4, reps: '6-8', rest_seconds: 240 },
          { exercise_name: 'Romanian Deadlift', sets: 3, reps: '8-10', rest_seconds: 180 },
          { exercise_name: 'Leg Press', sets: 3, reps: '10-15', rest_seconds: 120 },
          { exercise_name: 'Leg Extension', sets: 3, reps: '12-15', rest_seconds: 90 },
          { exercise_name: 'Lying Leg Curl', sets: 3, reps: '12-15', rest_seconds: 90 },
          { exercise_name: 'Standing Calf Raise', sets: 4, reps: '12-15', rest_seconds: 60 },
        ],
      },
      {
        day_number: 4,
        label: 'Push B',
        muscle_groups: ['Chest', 'Shoulders', 'Triceps'],
        exercises: [
          { exercise_name: 'Incline Barbell Bench Press', sets: 4, reps: '6-8', rest_seconds: 180 },
          { exercise_name: 'Dumbbell Bench Press', sets: 3, reps: '8-12', rest_seconds: 120 },
          { exercise_name: 'High Cable Flyes', sets: 3, reps: '12-15', rest_seconds: 90 },
          { exercise_name: 'Arnold Press', sets: 3, reps: '10-12', rest_seconds: 120 },
          { exercise_name: 'Lateral Raise', sets: 4, reps: '15-20', rest_seconds: 60 },
          { exercise_name: 'Overhead Tricep Extension', sets: 3, reps: '12-15', rest_seconds: 60 },
          { exercise_name: 'Rope Pushdown', sets: 3, reps: '12-15', rest_seconds: 60 },
        ],
      },
      {
        day_number: 5,
        label: 'Pull B',
        muscle_groups: ['Back', 'Biceps', 'Rear Delts'],
        exercises: [
          { exercise_name: 'Pull-Up', sets: 4, reps: '6-10', rest_seconds: 150 },
          { exercise_name: 'Dumbbell Row', sets: 4, reps: '8-10', rest_seconds: 120 },
          { exercise_name: 'Lat Pulldown', sets: 3, reps: '10-12', rest_seconds: 90 },
          { exercise_name: 'Straight-Arm Pulldown', sets: 3, reps: '12-15', rest_seconds: 60 },
          { exercise_name: 'Rear Delt Flyes', sets: 4, reps: '15-20', rest_seconds: 60 },
          { exercise_name: 'Incline Dumbbell Curl', sets: 3, reps: '10-12', rest_seconds: 90 },
          { exercise_name: 'Cable Curl', sets: 3, reps: '12-15', rest_seconds: 60 },
        ],
      },
      {
        day_number: 6,
        label: 'Legs B',
        muscle_groups: ['Quads', 'Hamstrings', 'Calves', 'Glutes'],
        exercises: [
          { exercise_name: 'Romanian Deadlift', sets: 4, reps: '8-10', rest_seconds: 180 },
          { exercise_name: 'Hack Squat', sets: 3, reps: '8-12', rest_seconds: 150 },
          { exercise_name: 'Bulgarian Split Squat', sets: 3, reps: '10-12', rest_seconds: 120 },
          { exercise_name: 'Leg Extension', sets: 3, reps: '15-20', rest_seconds: 60 },
          { exercise_name: 'Seated Leg Curl', sets: 3, reps: '12-15', rest_seconds: 90 },
          { exercise_name: 'Seated Calf Raise', sets: 4, reps: '15-20', rest_seconds: 60 },
          { exercise_name: 'Hip Thrust', sets: 3, reps: '12-15', rest_seconds: 90 },
        ],
      },
    ],
  },
  {
    name: "5/3/1 — Jim Wendler's Method",
    description: "The gold standard strength program. Four days of heavy main lifts with assistance work. Built around progressive overload.",
    days_per_week: 4,
    difficulty: 'intermediate',
    program_days_json: [
      {
        day_number: 1,
        label: 'Press Day',
        muscle_groups: ['Shoulders', 'Triceps'],
        exercises: [
          { exercise_name: 'Overhead Press (OHP)', sets: 3, reps: '5/3/1+', rest_seconds: 240, notes: 'Week 1: 65%/75%/85%×5+, Week 2: 70%/80%/90%×3+, Week 3: 75%/85%/95%×1+' },
          { exercise_name: 'Dumbbell Bench Press', sets: 5, reps: '10', rest_seconds: 90 },
          { exercise_name: 'Lat Pulldown', sets: 5, reps: '10', rest_seconds: 90 },
          { exercise_name: 'Lateral Raise', sets: 5, reps: '15', rest_seconds: 60 },
          { exercise_name: 'Tricep Pushdown', sets: 5, reps: '15', rest_seconds: 60 },
        ],
      },
      {
        day_number: 2,
        label: 'Deadlift Day',
        muscle_groups: ['Back', 'Hamstrings', 'Glutes'],
        exercises: [
          { exercise_name: 'Deadlift', sets: 3, reps: '5/3/1+', rest_seconds: 300, notes: 'Follow the 5/3/1 percentages for your working max.' },
          { exercise_name: 'Barbell Back Squat', sets: 5, reps: '10', rest_seconds: 180 },
          { exercise_name: 'Dumbbell Row', sets: 5, reps: '10', rest_seconds: 90 },
          { exercise_name: 'Hyperextension', sets: 5, reps: '10', rest_seconds: 60 },
          { exercise_name: 'Plank', sets: 5, reps: '30s', rest_seconds: 60 },
        ],
      },
      {
        day_number: 3,
        label: 'Bench Day',
        muscle_groups: ['Chest', 'Triceps'],
        exercises: [
          { exercise_name: 'Barbell Bench Press', sets: 3, reps: '5/3/1+', rest_seconds: 240, notes: 'Follow the 5/3/1 percentages for your working max.' },
          { exercise_name: 'Incline Dumbbell Press', sets: 5, reps: '10', rest_seconds: 90 },
          { exercise_name: 'Barbell Row', sets: 5, reps: '10', rest_seconds: 90 },
          { exercise_name: 'Face Pull', sets: 5, reps: '15', rest_seconds: 60 },
          { exercise_name: 'Barbell Curl', sets: 5, reps: '15', rest_seconds: 60 },
        ],
      },
      {
        day_number: 4,
        label: 'Squat Day',
        muscle_groups: ['Quads', 'Glutes', 'Hamstrings'],
        exercises: [
          { exercise_name: 'Barbell Back Squat', sets: 3, reps: '5/3/1+', rest_seconds: 300, notes: 'Follow the 5/3/1 percentages for your working max.' },
          { exercise_name: 'Romanian Deadlift', sets: 5, reps: '10', rest_seconds: 120 },
          { exercise_name: 'Leg Press', sets: 5, reps: '10', rest_seconds: 90 },
          { exercise_name: 'Leg Curl', sets: 5, reps: '10', rest_seconds: 60 },
          { exercise_name: 'Standing Calf Raise', sets: 5, reps: '15', rest_seconds: 60 },
        ],
      },
    ],
  },
  {
    name: 'Upper/Lower Split — 4-Day',
    description: 'Train upper body twice and lower body twice per week. Perfect balance of frequency and volume.',
    days_per_week: 4,
    difficulty: 'beginner',
    program_days_json: [
      {
        day_number: 1,
        label: 'Upper A (Strength)',
        muscle_groups: ['Chest', 'Back', 'Shoulders', 'Biceps', 'Triceps'],
        exercises: [
          { exercise_name: 'Barbell Bench Press', sets: 4, reps: '6-8', rest_seconds: 180 },
          { exercise_name: 'Barbell Row', sets: 4, reps: '6-8', rest_seconds: 180 },
          { exercise_name: 'Overhead Press (OHP)', sets: 3, reps: '8-10', rest_seconds: 120 },
          { exercise_name: 'Pull-Up', sets: 3, reps: '6-10', rest_seconds: 120 },
          { exercise_name: 'EZ Bar Curl', sets: 3, reps: '10-12', rest_seconds: 90 },
          { exercise_name: 'Skull Crusher', sets: 3, reps: '10-12', rest_seconds: 90 },
        ],
      },
      {
        day_number: 2,
        label: 'Lower A (Strength)',
        muscle_groups: ['Quads', 'Hamstrings', 'Glutes', 'Calves'],
        exercises: [
          { exercise_name: 'Barbell Back Squat', sets: 4, reps: '6-8', rest_seconds: 240 },
          { exercise_name: 'Romanian Deadlift', sets: 3, reps: '8-10', rest_seconds: 180 },
          { exercise_name: 'Leg Press', sets: 3, reps: '10-12', rest_seconds: 120 },
          { exercise_name: 'Leg Curl', sets: 3, reps: '10-12', rest_seconds: 90 },
          { exercise_name: 'Standing Calf Raise', sets: 4, reps: '15', rest_seconds: 60 },
        ],
      },
      {
        day_number: 3,
        label: 'Upper B (Hypertrophy)',
        muscle_groups: ['Chest', 'Back', 'Shoulders', 'Biceps', 'Triceps'],
        exercises: [
          { exercise_name: 'Incline Dumbbell Press', sets: 4, reps: '10-12', rest_seconds: 90 },
          { exercise_name: 'Seated Cable Row', sets: 4, reps: '10-12', rest_seconds: 90 },
          { exercise_name: 'Lateral Raise', sets: 4, reps: '15-20', rest_seconds: 60 },
          { exercise_name: 'Lat Pulldown', sets: 3, reps: '10-12', rest_seconds: 90 },
          { exercise_name: 'Dumbbell Curl', sets: 3, reps: '12-15', rest_seconds: 60 },
          { exercise_name: 'Tricep Pushdown', sets: 3, reps: '12-15', rest_seconds: 60 },
          { exercise_name: 'Face Pull', sets: 3, reps: '15-20', rest_seconds: 60 },
        ],
      },
      {
        day_number: 4,
        label: 'Lower B (Hypertrophy)',
        muscle_groups: ['Quads', 'Hamstrings', 'Glutes', 'Calves'],
        exercises: [
          { exercise_name: 'Bulgarian Split Squat', sets: 3, reps: '10-12', rest_seconds: 120 },
          { exercise_name: 'Deadlift', sets: 3, reps: '6-8', rest_seconds: 180 },
          { exercise_name: 'Hack Squat', sets: 3, reps: '10-15', rest_seconds: 90 },
          { exercise_name: 'Leg Extension', sets: 3, reps: '15-20', rest_seconds: 60 },
          { exercise_name: 'Hip Thrust', sets: 3, reps: '12-15', rest_seconds: 90 },
          { exercise_name: 'Seated Calf Raise', sets: 4, reps: '15-20', rest_seconds: 60 },
        ],
      },
    ],
  },
  {
    name: 'Full Body 3×/Week',
    description: 'Train your whole body three times per week. Ideal for beginners and those with limited time.',
    days_per_week: 3,
    difficulty: 'beginner',
    program_days_json: [
      {
        day_number: 1,
        label: 'Full Body A',
        muscle_groups: ['Full Body'],
        exercises: [
          { exercise_name: 'Barbell Back Squat', sets: 3, reps: '8-10', rest_seconds: 180 },
          { exercise_name: 'Barbell Bench Press', sets: 3, reps: '8-10', rest_seconds: 150 },
          { exercise_name: 'Barbell Row', sets: 3, reps: '8-10', rest_seconds: 150 },
          { exercise_name: 'Overhead Press (OHP)', sets: 3, reps: '8-10', rest_seconds: 120 },
          { exercise_name: 'Barbell Curl', sets: 2, reps: '10-12', rest_seconds: 90 },
          { exercise_name: 'Tricep Pushdown', sets: 2, reps: '10-12', rest_seconds: 90 },
          { exercise_name: 'Plank', sets: 3, reps: '30-45s', rest_seconds: 60 },
        ],
      },
      {
        day_number: 2,
        label: 'Full Body B',
        muscle_groups: ['Full Body'],
        exercises: [
          { exercise_name: 'Deadlift', sets: 3, reps: '6-8', rest_seconds: 210 },
          { exercise_name: 'Incline Dumbbell Press', sets: 3, reps: '8-12', rest_seconds: 120 },
          { exercise_name: 'Pull-Up', sets: 3, reps: '5-8', rest_seconds: 150 },
          { exercise_name: 'Lateral Raise', sets: 3, reps: '12-15', rest_seconds: 60 },
          { exercise_name: 'Romanian Deadlift', sets: 3, reps: '10-12', rest_seconds: 120 },
          { exercise_name: 'Standing Calf Raise', sets: 3, reps: '15', rest_seconds: 60 },
          { exercise_name: 'Crunch', sets: 3, reps: '15-20', rest_seconds: 60 },
        ],
      },
      {
        day_number: 3,
        label: 'Full Body C',
        muscle_groups: ['Full Body'],
        exercises: [
          { exercise_name: 'Front Squat', sets: 3, reps: '8-10', rest_seconds: 180 },
          { exercise_name: 'Dumbbell Bench Press', sets: 3, reps: '10-12', rest_seconds: 120 },
          { exercise_name: 'Seated Cable Row', sets: 3, reps: '10-12', rest_seconds: 120 },
          { exercise_name: 'Arnold Press', sets: 3, reps: '10-12', rest_seconds: 90 },
          { exercise_name: 'Dumbbell Curl', sets: 2, reps: '12-15', rest_seconds: 60 },
          { exercise_name: 'Skull Crusher', sets: 2, reps: '12-15', rest_seconds: 60 },
          { exercise_name: 'Hip Thrust', sets: 3, reps: '12-15', rest_seconds: 90 },
        ],
      },
    ],
  },
];
